`ifndef PROTOCOL_GENERATED_SVH
`define PROTOCOL_GENERATED_SVH

`define GFX_TRANSPORT_VERSION 8'h02
`define GFX_COMMAND_VERSION 8'h02
`define GFX_STATUS_VERSION 8'h02
`define GFX_MAX_DATAGRAM_BYTES 1400
`define GFX_TRANSPORT_HEADER_BYTES 12
`define GFX_PACKET_ACK_BYTES 20
`define GFX_FRAME_STATUS_BYTES 68
`define GFX_RECEIVE_FIFO_BYTES 2048
`define GFX_MESH_HANDLE_COUNT 16
`define GFX_VERTICES_PER_MESH 128
`define GFX_TRIANGLES_PER_MESH 256
`define GFX_SYSTEM_CLOCK_HZ 50000000
`define GFX_RENDER_WIDTH 320
`define GFX_RENDER_HEIGHT 240
`define GFX_DISPLAY_WIDTH 640
`define GFX_DISPLAY_HEIGHT 480
`define GFX_DEFAULT_UDP_PORT 4000
`define GFX_COMMAND_MAGIC_0 8'h47
`define GFX_COMMAND_MAGIC_1 8'h46
`define GFX_TRANSPORT_MAGIC_0 8'h47
`define GFX_TRANSPORT_MAGIC_1 8'h50
`define GFX_STATUS_MAGIC_0 8'h47
`define GFX_STATUS_MAGIC_1 8'h53
`define GFX_STATUS_EVENT_PACKET_ACKNOWLEDGED 8'd1
`define GFX_STATUS_EVENT_FRAME_DISPLAYED 8'd2
`define GFX_STATUS_ACCEPTED 32'h00000001
`define GFX_STATUS_DUPLICATE 32'h00000002
`define GFX_STATUS_BUSY 32'h00000004
`define GFX_STATUS_SEQUENCE_ERROR 32'h00000008
`define GFX_STATUS_MALFORMED 32'h00000010
`define GFX_STATUS_OVERFLOW 32'h00000020
`define GFX_STATUS_DECODER_ERROR 32'h00000100
`define GFX_STATUS_COMMAND_ERROR 32'h00000200
`define GFX_STATUS_RECEIVE_OVERFLOW 32'h00000400
`define GFX_BEGIN_FRAME_PAYLOAD_BYTES 4
`define GFX_DRAW_TRIANGLE_PAYLOAD_BYTES 19
`define GFX_END_FRAME_PAYLOAD_BYTES 0
`define GFX_SET_PALETTE_PAYLOAD_BYTES 4
`define GFX_DEFINE_MESH_PAYLOAD_BYTES 5
`define GFX_UPLOAD_VERTEX_PAYLOAD_BYTES 8
`define GFX_UPLOAD_INDEX_PAYLOAD_BYTES 7
`define GFX_DRAW_MESH_PAYLOAD_BYTES 25
`define GFX_SET_VIEW_MATRIX_PAYLOAD_BYTES 24
`define GFX_SET_PROJECTION_PAYLOAD_BYTES 10

`define GFX_WIRE_CMD_BEGIN_FRAME 8'd1
`define GFX_WIRE_CMD_DRAW_TRIANGLE 8'd2
`define GFX_WIRE_CMD_END_FRAME 8'd3
`define GFX_WIRE_CMD_SET_PALETTE 8'd4
`define GFX_WIRE_CMD_DEFINE_MESH 8'd5
`define GFX_WIRE_CMD_UPLOAD_VERTEX 8'd6
`define GFX_WIRE_CMD_UPLOAD_INDEX 8'd7
`define GFX_WIRE_CMD_DRAW_MESH 8'd8
`define GFX_WIRE_CMD_UPLOAD_VERTICES 8'd9
`define GFX_WIRE_CMD_UPLOAD_INDICES 8'd10
`define GFX_WIRE_CMD_SET_VIEW_MATRIX 8'd11
`define GFX_WIRE_CMD_SET_PROJECTION 8'd12

`endif
